---
extends: default

# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  comments: disable
  document-start: disable
  empty-lines:
    level: warning
  indentation:
    spaces: consistent
  line-length: disable
