name: Dependencies Reviewer

# --------------------------------------------------------------------------
# This workflow is only run when explicitly called by another workflow.
# --------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      review_conclusion:
        description: "Conclusion from the dependencies review process"
        value: ${{ env.REVIEW_STEP }}
      review_summary:
        description: "Summary from the dependencies review process"
        value: ${{ env.REVIEW_SUMMARY }}

env:
  MIN_SCORECARD_LEVEL: '5'

# This workflow is passive so ensure the minimal permissions even if the
# inherited token is more lenient.
permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  dependencies_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.repository.full_name }} # Checkout the caller repo
          fetch-depth: 0 # This may also capture vulnerabilities unrelated to the PR.

      - name: Run Dependency Review
        id: dependency_review
        uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1
        with:
          show-openssf-scorecard: true
          warn-on-openssf-scorecard-level: ${{ env.MIN_SCORECARD_LEVEL }}
        continue-on-error: true

      - name: Set Default Review Status (Success/Neutral)
        id: set_default_status
        if: ${{ always() && steps.dependency_review.outcome != 'failure' }}
        env:
          REVIEW_COMMENT: ${{ steps.dependency_review.outputs.comment-content }}
        shell: bash
        run: |
          echo "REVIEW_STEP=success" >> "$GITHUB_ENV"
          echo "REVIEW_SUMMARY='$REVIEW_COMMENT'" >> "$GITHUB_ENV"

      - name: Set Failed Review Status
        id: set_failure_status
        if: ${{ steps.dependency_review.conclusion == 'failure' }}
        shell: bash
        run: |
          echo "REVIEW_STEP=failure" >> "$GITHUB_ENV"
          echo "REVIEW_SUMMARY=empty" >> "$GITHUB_ENV"
